### ISSUE TITLE
sleuthkit 4.8.0 fails to compile with LLVM

### ISSUE THREAD

**Issue by ant1** [sleuthkit/sleuthkit#1794]
sleuthkit 4.8.0 fails to compile with LLVM

Here is the error with LLVM 8.0.1:

```
Making all in pool
/bin/sh ../../libtool  --tag=CXX    --mode=compile c++ -std=c++14 -DHAVE_CONFIG_H  -I. -I../../tsk   -I../.. -I./../.. -Wall -D_THREAD_SAFE -pthread -I/usr/local/include  -Wall -Wextra -Werror -g -O2 -MT pool_open.lo -MD -MP -MF .deps/pool_open.Tpo -c -o pool_open.lo pool_open.cpp
libtool: compile:  c++ -std=c++14 -DHAVE_CONFIG_H -I. -I../../tsk -I../.. -I./../.. -Wall -D_THREAD_SAFE -pthread -I/usr/local/include -Wall -Wextra -Werror -g -O2 -MT pool_open.lo -MD -MP -MF .deps/pool_open.Tpo -c pool_open.cpp  -fPIC -DPIC -o .libs/pool_open.o
In file included from pool_open.cpp:1:
In file included from ./../fs/tsk_apfs.hpp:5:
./../fs/../pool/tsk_apfs.hpp:38:14: error: explicitly defaulted move assignment operator is implicitly deleted
      [-Werror,-Wdefaulted-function-deleted]
  APFSBlock &operator=(APFSBlock &&) = default;
             ^
./../fs/../pool/tsk_apfs.hpp:23:19: note: move assignment operator of 'APFSBlock' is implicitly deleted because field '_pool'
      is of reference type 'const APFSPool &'
  const APFSPool &_pool;
                  ^
In file included from pool_open.cpp:1:
./../fs/tsk_apfs.hpp:576:3: error: explicitly defaulted copy constructor is implicitly deleted
      [-Werror,-Wdefaulted-function-deleted]
  APFSJObjBtreeNode(const APFSJObjBtreeNode &) = default;
  ^
./../fs/tsk_apfs.hpp:569:27: note: copy constructor of 'APFSJObjBtreeNode' is implicitly deleted because base class
      'APFSBtreeNode<>' has a deleted copy constructor
class APFSJObjBtreeNode : public APFSBtreeNode<> {
                          ^
./../fs/tsk_apfs.hpp:338:23: note: copy constructor of 'APFSBtreeNode<memory_view, memory_view>' is implicitly deleted because
      base class 'APFSObject' has a deleted copy constructor
class APFSBtreeNode : public APFSObject, public APFSOmap::node_tag {
                      ^
./../fs/tsk_apfs.hpp:40:20: note: copy constructor of 'APFSObject' is implicitly deleted because base class 'APFSBlock' has a
      deleted copy constructor
class APFSObject : public APFSBlock {
                   ^
./../fs/../pool/tsk_apfs.hpp:30:3: note: 'APFSBlock' has been explicitly marked deleted here
  APFSBlock(const APFSBlock &) = delete;
  ^
In file included from pool_open.cpp:1:
./../fs/tsk_apfs.hpp:577:22: error: explicitly defaulted copy assignment operator is implicitly deleted
      [-Werror,-Wdefaulted-function-deleted]
  APFSJObjBtreeNode &operator=(const APFSJObjBtreeNode &) = default;
                     ^
./../fs/tsk_apfs.hpp:569:27: note: copy assignment operator of 'APFSJObjBtreeNode' is implicitly deleted because base class
      'APFSBtreeNode<>' has a deleted copy assignment operator
class APFSJObjBtreeNode : public APFSBtreeNode<> {
                          ^
./../fs/tsk_apfs.hpp:338:23: note: copy assignment operator of 'APFSBtreeNode<memory_view, memory_view>' is implicitly deleted
      because base class 'APFSObject' has a deleted copy assignment operator
class APFSBtreeNode : public APFSObject, public APFSOmap::node_tag {
                      ^
./../fs/tsk_apfs.hpp:40:20: note: copy assignment operator of 'APFSObject' is implicitly deleted because base class 'APFSBlock'
      has a deleted copy assignment operator
class APFSObject : public APFSBlock {
                   ^
./../fs/../pool/tsk_apfs.hpp:31:14: note: 'operator=' has been explicitly marked deleted here
  APFSBlock &operator=(const APFSBlock &) = delete;
             ^
In file included from pool_open.cpp:1:
./../fs/tsk_apfs.hpp:580:22: error: explicitly defaulted move assignment operator is implicitly deleted
      [-Werror,-Wdefaulted-function-deleted]
  APFSJObjBtreeNode &operator=(APFSJObjBtreeNode &&) = default;
                     ^
./../fs/tsk_apfs.hpp:569:27: note: move assignment operator of 'APFSJObjBtreeNode' is implicitly deleted because base class
      'APFSBtreeNode<>' has a deleted move assignment operator
class APFSJObjBtreeNode : public APFSBtreeNode<> {
                          ^
./../fs/tsk_apfs.hpp:338:23: note: copy assignment operator of 'APFSBtreeNode<memory_view, memory_view>' is implicitly deleted
      because base class 'APFSObject' has a deleted copy assignment operator
class APFSBtreeNode : public APFSObject, public APFSOmap::node_tag {
                      ^
./../fs/tsk_apfs.hpp:40:20: note: copy assignment operator of 'APFSObject' is implicitly deleted because base class 'APFSBlock'
      has a deleted copy assignment operator
class APFSObject : public APFSBlock {
                   ^
./../fs/../pool/tsk_apfs.hpp:31:14: note: 'operator=' has been explicitly marked deleted here
  APFSBlock &operator=(const APFSBlock &) = delete;
             ^
4 errors generated.
```

Removing the Werror from the pool Makefile allows it to build,  but maybe those warnings are worth fixing?

**Comment by uckelman-sf** [comment]
I believe these are fixed in `3abc156` on the develop branch.

**Comment by ant1** [comment]
I confirm that the develop branch builds fine with LLVM 8.0.1

**Comment by esaunders** [comment]
FYI: the fix was also pulled into the release-4.8.0 branch and the 4.8.0 release tarball should have them.
Can you close this issue if you are satisfied with the fix?
Thanks.
