### ISSUE TITLE
fiwalk compile error

### ISSUE THREAD

**Issue by bcarrier** [sleuthkit/sleuthkit#324]
g++ -DHAVE_CONFIG_H -I. -I../../../tsk  -I../../.. -Wall -D_THREAD_SAFE -pthread -I/usr/local/include  -g -O2 -MT plugin.o -MD -MP -MF .deps/plugin.Tpo -c -o plugin.o plugin.cpp
plugin.cpp: In function ‘void plugin_process(const std::string&)’:
plugin.cpp:170: error: no matching function for call to ‘getline(char*_, size_t_, FILE*&)’

This started with merge from #318. On my OS X 10.6.8.  Works on 10.8.5.
